# [ 📄 backtesting/reason_codes.py ]

class ReasonCode:
    # --- 진입 (Entry) ---
    ENTRY_SCORE_PASS = "ENTRY_SCORE_PASS"
    HEDGE_ENTER = "HEDGE_ENTER"
    SWITCH_IN = "SWITCH_IN"

    # --- 매도 (Exit) ---
    EXIT_SIGNAL = "EXIT_SIGNAL"
    EXIT_TRAILING_STOP = "EXIT_TRAILING_STOP"
    HEDGE_EXIT = "HEDGE_EXIT"
    SWITCH_OUT = "SWITCH_OUT"
    HEDGE_LIQUIDATION = "HEDGE_LIQ"

    # --- 탈락/차단 (Reject/Block) ---
    REJECT_BY_PANIC = "REJECT_BY_PANIC"
    REJECT_LOW_SCORE = "REJECT_LOW_SCORE"
    ORDER_SKIPPED_NO_CASH = "ORDER_SKIPPED_NO_CASH"
    ORDER_SKIPPED_MAX_POS = "ORDER_SKIPPED_MAX_POS"
    BUY_BLOCKED_BY_CASH_BUFFER = "BUY_BLOCKED_BY_CASH_BUFFER"
    INSUFFICIENT_BUYING_POWER = "INSUFFICIENT_BUYING_POWER"
    SWITCH_FAILED = "SWITCH_FAILED"
